name: panora
description: online bookstore app

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  bottom_navy_bar: ^5.2.2
  provider: ^3.2.0
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - image/loading.png


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

